spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      instanceProfile: true
      accessKey: ${AWS_ACCESS}
      secretKey: ${AWS_SECRET}
